### ISSUE TITLE
NC Backup fails to start

### ISSUE THREAD

**Issue by jds11111** [Sebclem/hassio-nextcloud-backup#128]
Logs leave this message:

[03:44:23] INFO: Starting Node...
> nexcloud-backup@0.8.0 start
> node ./bin/www
[2022-04-24 03:44:27] [info]: 	Log level: info
[2022-04-24 03:44:27] [info]: 	Backup timeout: 5400000
[2022-04-24 03:44:27] [error]: 	uncaughtException: Unexpected token  in JSON at position 0
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at getStatus (/opt/nextcloud_backup/tools/status.js:29:17)
    at Object.init (/opt/nextcloud_backup/tools/status.js:16:23)
    at Object.<anonymous> (/opt/nextcloud_backup/app.js:82:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)

**Comment by jds11111** [comment]
Reinstalling gets it running for a bit, but still dies and refuses to restart. Setting the log levels higher does not give much more information.

**Comment by Sebclem** [comment]
I need to finish / merge #124 that will normally fix this.

I will take a look at this this weekend

**Comment by Sebclem** [comment]
Can you retry with the last version (0.17.2) ?

**Comment by jds11111** [comment]
It has been running without crashing for a couple of days, so the new version might be fixed. Actually, there is another version now, too, which I have installed.  I will report back if there are any problems, but am assuming it is all good now.  Thank you!

**Comment by Sebclem** [comment]
Perfect! I'm closing this issue for now, but feel free to reopen it if this bug comes back
