### ISSUE TITLE
Boot loop, AddOn never comes up

### ISSUE THREAD

**Issue by strandbein** [Sebclem/hassio-nextcloud-backup#134]
After updating to current version following error-log appears. The add-on never comes up, neither web-ui.

-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.6  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.4.7
 Home Assistant Supervisor: 2022.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:36:08] INFO: Starting Node...
[2022-05-02 12:36:13] [info]: 	Log level: info
[2022-05-02 12:36:13] [info]: 	Backup timeout: 5400000
[2022-05-02 12:36:13] [info]: 	Satus : Go !
[2022-05-02 12:36:13] [info]: 	Initializing and checking webdav client...
[2022-05-02 12:36:13] [info]: 	Starting auto clean cron...
[2022-05-02 12:36:14] [info]: 	Starting Cron...
[2022-05-02 12:36:14] [error]: 	uncaughtException: this.cronJob.nextDate(...).format is not a function
TypeError: this.cronJob.nextDate(...).format is not a function
    at CronContainer.updateNextDate (file:///opt/nextcloud_backup/tools/cronTools.js:71:45)
    at CronContainer.init (file:///opt/nextcloud_backup/tools/cronTools.js:65:14)
    at file:///opt/nextcloud_backup/app.js:119:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
[2022-05-02 12:36:14] [info]: 	Hassio API : Go !

[2022-05-02 12:36:22] [info]: 	Hassio API : Go !
[12:36:25] INFO: Starting Node...
[2022-05-02 12:36:30] [info]: 	Log level: info
[2022-05-02 12:36:30] [info]: 	Backup timeout: 5400000
[2022-05-02 12:36:30] [info]: 	Satus : Go !
[2022-05-02 12:36:30] [info]: 	Initializing and checking webdav client...
[2022-05-02 12:36:30] [info]: 	Starting auto clean cron...
[2022-05-02 12:36:30] [info]: 	Starting Cron...
[2022-05-02 12:36:30] [error]: 	uncaughtException: this.cronJob.nextDate(...).format is not a function
TypeError: this.cronJob.nextDate(...).format is not a function
    at CronContainer.updateNextDate (file:///opt/nextcloud_backup/tools/cronTools.js:71:45)
    at CronContainer.init (file:///opt/nextcloud_backup/tools/cronTools.js:65:14)
    at file:///opt/nextcloud_backup/app.js:119:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
[2022-05-02 12:36:30] [info]: 	Hassio API : Go !
[12:36:34] INFO: Starting Node...
[2022-05-02 12:36:38] [info]: 	Log level: info
[2022-05-02 12:36:38] [info]: 	Backup timeout: 5400000
[2022-05-02 12:36:38] [info]: 	Satus : Go !
[2022-05-02 12:36:38] [info]: 	Initializing and checking webdav client...
[2022-05-02 12:36:39] [info]: 	Starting auto clean cron...
[2022-05-02 12:36:39] [info]: 	Starting Cron...
[2022-05-02 12:36:39] [error]: 	uncaughtException: this.cronJob.nextDate(...).format is not a function
TypeError: this.cronJob.nextDate(...).format is not a function
    at CronContainer.updateNextDate (file:///opt/nextcloud_backup/tools/cronTools.js:71:45)
    at CronContainer.init (file:///opt/nextcloud_backup/tools/cronTools.js:65:14)
    at file:///opt/nextcloud_backup/app.js:119:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
[2022-05-02 12:36:39] [info]: 	Hassio API : Go !

**Comment by Sebclem** [comment]
Please upgrade to 0.17.2, this was caused by a dependency upgrade, it's fixed with the 0.17.2

**Comment by strandbein** [comment]
No all is fine, thank you!
