### ISSUE TITLE
[error]: uncaughtException: Cannot read property 'statusCode' of undefined TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by tomecki88** [Sebclem/hassio-nextcloud-backup#17]
Hi,
firstly, thank you for your great addon!
Secondly I'm having problems to send a snapshot to NC. It was never succesful (I'm using addon from 3 days) but no manual and no auto snapshot are send to NC. Always I'm getting this same error (log attached below).

My HA setup:
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.126-v7
python_version | 3.7.7
supervisor | 227
timezone | Europe/Warsaw
version | 0.111.3
virtualenv | false

Log from addon:
```
[01:00:04] INFO: Starting Node...
> nexcloud-backup@0.0.0 start /opt/nextcloud_backup
> node --inspect=0.0.0.0:9226 ./bin/www 
Debugger listening on ws://0.0.0.0:9226/17c77a6a-5a5a-4df1-9ff2-156414f92769
For help, see: https://nodejs.org/en/docs/inspector
[2020-06-18 01:00:11] [info]: Satus : Go !
[2020-06-18 01:00:11] [info]: Initilizing and checking webdav client...
[2020-06-18 01:00:11] [info]: Starting auto clean cron...
[2020-06-18 01:00:11] [info]: Starting Cron...
[2020-06-18 01:00:12] [info]: Hassio API : Go !
[2020-06-18 01:00:13] [debug]: Nextcloud connection:  Success !
[2020-06-18 01:00:14] [info]: Nextcloud connection : Go !
[2020-06-18 02:00:00] [debug]: Cron triggered !
[2020-06-18 02:00:00] [info]: Creating new snapshot...
[2020-06-18 02:20:01] [error]: uncaughtException: Cannot read property 'statusCode' of undefined
TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.post [as _callback] (/opt/nextcloud_backup/tools/hassioApiTools.js:173:26)
    at self.callback (/opt/nextcloud_backup/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at ClientRequest.<anonymous> (/opt/nextcloud_backup/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:443:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nexcloud-backup@0.0.0 start: `node --inspect=0.0.0.0:9226 ./bin/www `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nexcloud-backup@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T00_20_04_209Z-debug.log
```

Thanks in advance for any help/fix.

**Comment by Sebclem** [comment]
Hi, thank you !

It's very strange, you have a time out after waiting 20min for the backup to be done by the supervisor.

When you do the backup manually via the home assistant's supervisor interface, is this working ? 
If yes, how many times it take to complete the backup?

**Comment by tomecki88** [comment]
Hi @Sebclem.
Manual snapshot from supervisor is working normally and it takes around 18-22 minutes to make whole backup.
Also this snapshot triggered from Nextcloud backup addon is finished and snapshot made properly.
I was trying to reinstall/change NC user but still I'm getting this error.

Thanks in advance for any help.

**Comment by Sebclem** [comment]
Ok, i will try to increase the timeout delay, it's 20min, maybe to short.

**Comment by tomecki88** [comment]
Hi @Sebclem . Thanks for new release with timeout value increase.
Now I'm getting following error (snapshot made but can't upload to Nextcloud):

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-run: applying... 
[fix-attrs.d] 10-run: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Nextcloud Backup
 Hass.io snapshot backup to Nextcloud
-----------------------------------------------------------
 Add-on version: 0.7.8
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[15:08:20] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant version: 0.111.4
 Supervisor version: 228
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:08:25] INFO: Starting Node...
> nexcloud-backup@0.0.0 start /opt/nextcloud_backup
> node --inspect=0.0.0.0:9226 ./bin/www 
Debugger listening on ws://0.0.0.0:9226/9d78b44e-7659-462f-9ced-7d0725f5416a
For help, see: https://nodejs.org/en/docs/inspector
[2020-07-04 15:11:18] [info]: Satus : Go !
[2020-07-04 15:11:18] [info]: Initilizing and checking webdav client...
[2020-07-04 15:11:18] [info]: Starting auto clean cron...
[2020-07-04 15:11:18] [info]: Starting Cron...
[2020-07-04 15:11:19] [info]: Hassio API : Go !
[2020-07-04 15:11:20] [debug]: Nextcloud connection:  Success !
[2020-07-04 15:11:21] [info]: Nextcloud connection : Go !
[2020-07-04 15:18:55] [info]: Creating new snapshot...
[2020-07-04 15:53:00] [info]: Snapshot created with id dd63f8b3
[2020-07-04 15:53:00] [info]: Downloading snapshot dd63f8b3...
[2020-07-04 15:53:00] [debug]: Snapshot size: 295.68
[2020-07-04 15:55:50] [info]: Download success !
[2020-07-04 15:55:50] [debug]: Snapshot dl size : 295.68359375
[2020-07-04 15:55:50] [info]: Uploading snap...
[2020-07-04 15:55:50] [error]: Fail to upload snapshot to nextcloud (Status code: 411) !
(node:357) UnhandledPromiseRejectionWarning: Fail to upload snapshot to nextcloud (Status code: 411) !
(node:357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Sebclem** [comment]
Can I have your nextcloud version?

**Comment by tomecki88** [comment]
Hi @Sebclem,
Sure, actually I'm using NC 18.0.4.

**Comment by Sebclem** [comment]
Are you using Lighttpd ?
I found a similar issue that mention Lighttpd : https://github.com/nextcloud/desktop/issues/1473

**Comment by tomecki88** [comment]
Hi @Sebclem,
no. I'm using Apache in version 2.2.34.

**Comment by Sebclem** [comment]
Did the recent update fix your issue ?
