### ISSUE TITLE
ENOTFOUND HTTPS

### ISSUE THREAD

**Issue by Tobus** [Sebclem/hassio-nextcloud-backup#228]
**Describe the bug**
I have a docker instance of Nextcloud behind Traefik. Webdav is working, also all Nextcloud clients.
When saving the settings of the Addon, it shows the error ENOTFOUND HTTPS. No entry in Nextcloud.log

**To Reproduce**
Setup Nextcloud behind Traefik
Enable WebDav
Enter in Addon url (eg nextcloud.yoururl.com)
Save

**Error log of Addon**
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
fix-attrs: info: applying /etc/fix-attrs.d/10-run
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
 Add-on: Nextcloud Backup
 Add-on version: 0.17.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.0
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to INFO
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nextcould_backup (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:20:17] INFO: Starting Node...
[2024-01-16 22:20:22] [info]: 	Log level: info
[2024-01-16 22:20:22] [info]: 	Backup timeout: 5400000
[2024-01-16 22:20:22] [info]: 	Satus : Go !
[2024-01-16 22:20:22] [info]: 	Initializing and checking webdav client...
[2024-01-16 22:20:22] [info]: 	Starting auto clean cron...
[2024-01-16 22:20:22] [info]: 	Starting Cron...
[2024-01-16 22:20:22] [info]: 	Hassio API : Go !
[2024-01-16 22:20:26] [error]: 	Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https)
[2024-01-16 22:20:26] [error]: 	Nextcloud connection : FAIL !
[2024-01-16 22:20:26] [error]: 	... Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https) !
[2024-01-16 22:20:26] [error]: 	uncaughtException: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/opt/nextcloud_backup/node_modules/express/lib/response.js:1150:12)
    at ServerResponse.json (/opt/nextcloud_backup/node_modules/express/lib/response.js:271:14)
    at ServerResponse.send (/opt/nextcloud_backup/node_modules/express/lib/response.js:162:21)
    at file:///opt/nextcloud_backup/routes/api.js:56:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[22:20:29] INFO: Starting Node...

**System information**
- Home Assistant Version : 2023.12.4
- Home Assistant Supervisor Version : 2023.12.0
- If any, reverse proxy in fort on Nextcloud : Traefik

**Additional context**
What can I do?

Best
Tbs

**Comment by Tobus** [comment]
Please close
