### ISSUE TITLE
Auto snapshots don't backup, but manual do

### ISSUE THREAD

**Issue by kicker334** [Sebclem/hassio-nextcloud-backup#23]
Noticed that the snapshots are being created but not uploaded. No 0kb files either.

**Comment by Sebclem** [comment]
Do you have any logs ?

**Comment by kicker334** [comment]
Yes, sorry. 

```
[2020-08-16 11:46:08] [info]: Satus : Go !
[2020-08-16 11:46:08] [info]: Initilizing and checking webdav client...
[2020-08-16 11:46:08] [info]: Starting auto clean cron...
[2020-08-16 11:46:08] [info]: Starting Cron...
[2020-08-16 11:46:08] [info]: Hassio API : Go !
[2020-08-16 11:46:09] [debug]: Nextcloud connection:  Success !
[2020-08-16 11:46:09] [info]: Nextcloud connection : Go !
[2020-08-16 11:59:41] [info]: Creating new snapshot...
[2020-08-16 12:00:36] [info]: Snapshot created with id eeaed6ed
[2020-08-16 12:00:36] [info]: Downloading snapshot eeaed6ed...
[2020-08-16 12:00:36] [debug]: Snapshot size: 22.94
[2020-08-16 12:00:36] [info]: Download success !
[2020-08-16 12:00:36] [debug]: Snapshot dl size : 22.939453125
[2020-08-16 12:00:39] [info]: Uploading snap...
[2020-08-16 12:00:51] [info]: Upload done...
[2020-08-16 12:00:52] [info]: ...Upload finish ! (status: 201)
[2020-08-16 12:00:52] [debug]: Snapshot size: 30.28
[2020-08-16 12:00:52] [debug]: Snapshot size: 29.98
[2020-08-16 12:00:52] [info]: Local clean done.
[2020-08-17 01:00:00] [debug]: Cron triggered !
[2020-08-17 01:00:00] [info]: Creating new snapshot...
[2020-08-17 01:00:00] [error]: uncaughtException: this.clean is not a function
TypeError: this.clean is not a function
    at CronJob._clean (/opt/nextcloud_backup/tools/cronTools.js:147:18)
    at CronJob.fireOnTick (/opt/nextcloud_backup/node_modules/cron/lib/cron.js:562:23)
    at Timeout.callbackWrapper [as _onTimeout] (/opt/nextcloud_backup/node_modules/cron/lib/cron.js:629:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2020-08-17 01:00:00] [info]: Local clean done.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nexcloud-backup@0.7.10 start: `node --inspect=0.0.0.0:9226 ./bin/www `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nexcloud-backup@0.7.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-17T05_00_03_440Z-debug.log
[01:00:03] INFO: Starting Node...
> nexcloud-backup@0.7.10 start /opt/nextcloud_backup
> node --inspect=0.0.0.0:9226 ./bin/www 
Debugger listening on ws://0.0.0.0:9226/a8246098-9d03-49d2-9c86-922072dba204
For help, see: https://nodejs.org/en/docs/inspector
[2020-08-17 01:00:18] [info]: Satus : Go !
[2020-08-17 01:00:18] [info]: Initilizing and checking webdav client...
[2020-08-17 01:00:18] [info]: Starting auto clean cron...
[2020-08-17 01:00:18] [info]: Starting Cron...
[2020-08-17 01:00:18] [info]: Hassio API : Go !
[2020-08-17 01:00:19] [debug]: Nextcloud connection:  Success !
[2020-08-17 01:00:19] [info]: Nextcloud connection : Go !
[2020-08-17 05:39:10] [info]: Downloading snapshot 21d16090...
[2020-08-17 05:39:10] [debug]: Snapshot size: 19.98
[2020-08-17 05:39:11] [info]: Download success !
[2020-08-17 05:39:11] [debug]: Snapshot dl size : 19.98046875
[2020-08-17 05:39:11] [info]: Uploading snap...
[2020-08-17 05:39:13] [info]: Upload done...
[2020-08-17 05:39:13] [info]: ...Upload finish ! (status: 201)
[2020-08-17 05:39:13] [debug]: Snapshot size: 22.24
[2020-08-17 05:39:13] [info]: Local clean done.
[2020-08-18 01:00:00] [debug]: Cron triggered !
[2020-08-18 01:00:00] [info]: Creating new snapshot...
[2020-08-18 01:00:00] [error]: uncaughtException: this.clean is not a function
TypeError: this.clean is not a function
    at CronJob._clean (/opt/nextcloud_backup/tools/cronTools.js:147:18)
    at CronJob.fireOnTick (/opt/nextcloud_backup/node_modules/cron/lib/cron.js:562:23)
    at Timeout.callbackWrapper [as _onTimeout] (/opt/nextcloud_backup/node_modules/cron/lib/cron.js:629:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2020-08-18 01:00:00] [info]: Local clean done.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nexcloud-backup@0.7.10 start: `node --inspect=0.0.0.0:9226 ./bin/www `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nexcloud-backup@0.7.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-18T05_00_03_303Z-debug.log
[01:00:03] INFO: Starting Node...
> nexcloud-backup@0.7.10 start /opt/nextcloud_backup
> node --inspect=0.0.0.0:9226 ./bin/www 
Debugger listening on ws://0.0.0.0:9226/9827e3d2-e272-4788-8ef9-63187504c728
For help, see: https://nodejs.org/en/docs/inspector
[2020-08-18 01:00:17] [info]: Satus : Go !
[2020-08-18 01:00:17] [info]: Initilizing and checking webdav client...
[2020-08-18 01:00:17] [info]: Starting auto clean cron...
[2020-08-18 01:00:17] [info]: Starting Cron...
[2020-08-18 01:00:17] [info]: Hassio API : Go !
[2020-08-18 01:00:18] [debug]: Nextcloud connection:  Success !
[2020-08-18 01:00:18] [info]: Nextcloud connection : Go !
```

**Comment by Sebclem** [comment]
I think i found the issue, i will make a release tomorrow
