### ISSUE TITLE
Response code 400 (Bad Request) before uploading is complete

### ISSUE THREAD

**Issue by GarfieldMZ** [Sebclem/hassio-nextcloud-backup#273]
**Describe the bug**
Fail to upload snapshot to nextcloud (HTTPError: Response code 400 (Bad Request))

**To Reproduce**
Just do a manual or automatic backup

**Expected behavior**
Scheduled or manual backup transfered completely to Nextcloud

**System information**
- Home Assistant Version : 2024.12.5
- Home Assistant Supervisor Version : 2024.12.0
- Nextcloud Version : Nextcloud Hub 9 (30.0.4)
- Addon version : 0.17.7
- If any, reverse proxy in fort on Nextcloud : none

**Additional context**
The NC Backup log shows:

```
[2024-12-25 04:00:00] [info]: 	Creating new snapshot...
[2024-12-25 04:06:21] [info]: 	Snapshot created with id 1cf7ef0e
[2024-12-25 04:06:21] [info]: 	Downloading snapshot 1cf7ef0e...
[2024-12-25 04:09:24] [info]: 	Download success !
[2024-12-25 04:09:24] [info]: 	Uploading snap...
[2024-12-25 04:15:30] [error]: 	Fail to upload snapshot to nextcloud (HTTPError: Response code 400 (Bad Request)) !
[2024-12-25 04:15:30] [error]: 	HTTPError: Response code 400 (Bad Request)
    at Request._onResponseBase (file:///opt/nextcloud_backup/node_modules/got/dist/source/core/index.js:684:31)
    at Request._onResponse (file:///opt/nextcloud_backup/node_modules/got/dist/source/core/index.js:743:24)
    at ClientRequest.<anonymous> (file:///opt/nextcloud_backup/node_modules/got/dist/source/core/index.js:761:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
[2024-12-25 04:15:30] [error]: 	uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Fail to upload snapshot to nextcloud (HTTPError: Response code 400 (Bad Request)) !".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Fail to upload snapshot to nextcloud (HTTPError: Response code 400 (Bad Request)) !".
[04:15:43] INFO: Starting Node...
``` 

The NC log shows:

```
Fehler	no app in context	
BadRequest
Expected filesize of 13195980800 bytes, but read (from Nextcloud client) and wrote (to Nextcloud storage) 12924575744 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

25.12.2024, 04:15:28	


Fehler	PHP	
fread(): Write of 8192 bytes failed with errno=28 No space left on device at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#55

25.12.2024, 04:15:28

```

The strange thing is that there is more than enough space on the drive where the file is to be saved.
The problem occurred on December 17th. No changes were made to NC or HA, only updates were installed.

Both are running on Proxmox. NC in an Container and HA as VM. The max file size in the php.ini of NC was set to 20G and unchanged before the issue startet 14 days ago. The disk space where /var/www/nextcloud/3rdparty/icewind/streams/src/ is located, havin the same available space as the data directory (/var/www/nextcloud/data).

**Comment by GarfieldMZ** [comment]
After searching unsuccessfully for a long time yesterday, I have finally found the problem. 
The problem is that NC first uploads the file to a temporary directory before moving it to the target directory. 
The temporary upload directory was on NC's system drive, which had no longer enough space for the backup. That is why the problem suddenly appeared without any changes.

**Solution:** 
created the temporary upload directory on the data drive and changed the directory in php.ini and config.php.
