### ISSUE TITLE
Error while trying to upload snapshot to HA

### ISSUE THREAD

**Issue by gitmirko** [Sebclem/hassio-nextcloud-backup#28]
Hi,
I've just tried to use the new feature "UPLOAD TO HA" and I'm getting the following error:
```
[2020-11-08 20:42:51] [info]: Downloading backup...
(node:251) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink './temp/restore_Nov-08-2020_20_42.tar'
    at Object.unlinkSync (fs.js:1136:3)
    at /opt/nextcloud_backup/tools/webdavTools.js:329:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Home Assistant 0.117.5
Addon version: 0.10.1

Best regards
Mirko

**Comment by Sebclem** [comment]
Hi,

It's normally fix with the last release.
Can you retry and let me know if it's good now ?

**Comment by gitmirko** [comment]
> Hi,
> 
> It's normally fix with the last release.
> Can you retry and let me know if it's good now ?

After updating to the last version it works.

Thank you very much
