### ISSUE TITLE
ERROR (MainThread) [aiohttp.server] Error handling request

### ISSUE THREAD

**Issue by poudenes** [Sebclem/hassio-nextcloud-backup#37]
Hi All,

When I access Nextcloud from the panel on left I see this error coming up many times:

```
2020-12-21 20:55:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 71, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
```

Nextcloud Add-On: Current version: 0.12.0 

```
Version | 2020.12.1
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.79-v8+
CPU Architecture | aarch64
Timezone | Europe/Amsterdam
```

**Comment by Sebclem** [comment]
Hi,
I have found some related topic on the net: 
- https://github.com/home-assistant/core/issues/43542
- https://community.home-assistant.io/t/ingress-error-help/266057
- https://community.home-assistant.io/t/aiohttp-server-error-handling-request-traceback/244701

I think it's more related to home assistant.
I will ask on the HA Discord

**Comment by stamandr** [comment]
Same problem for me. Nothing but DuckDNS and LetsEncrypt install....

2021-03-07 09:26:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by supermarkert** [comment]
I'm getting the same thing, running HAOS and latest core-2021.4.3. This error is happening several times a second and filling my logs. Full error:

`Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:393
First occurred: 1:47:45 PM (8 occurrences)
Last logged: 1:47:59 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
`

**Comment by zuhair68** [comment]
Same problem ...

**Comment by guineau** [comment]
Same problem

**Comment by Malvu** [comment]
Same problem
