### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by macsatcom** [Sebclem/hassio-nextcloud-backup#84]
I managed to make nextcloud backup login to my nextcloud (I can tell since it created the directories "auto" and "manual" on nextcloud).

I cannot make it actually backup, just hangs on "waiting". I see this in the log:

`-----------------------------------------------------------
 Add-on: Nextcloud Backup
 Easily backup your Home Assistant snapshots to Nextcloud
-----------------------------------------------------------
 Add-on version: 0.16.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.6
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:14:40] INFO: Starting Node...
> nexcloud-backup@0.8.0 start
> node ./bin/www
[2021-09-14 09:14:47] [error]: 	uncaughtException: Invalid time value
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.publish_state (/opt/nextcloud_backup/tools/hassioApiTools.js:554:87)
    at setStatus (/opt/nextcloud_backup/tools/status.js:37:28)
    at Object.init (/opt/nextcloud_backup/tools/status.js:20:13)
    at Object.<anonymous> (/opt/nextcloud_backup/app.js:77:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[09:14:51] INFO: Starting Node...
> nexcloud-backup@0.8.0 start
> node ./bin/www
[2021-09-14 09:14:55] [info]: 	Satus : Go !
[2021-09-14 09:14:55] [info]: 	Initializing and checking webdav client...
[2021-09-14 09:14:56] [info]: 	Starting auto clean cron...
[2021-09-14 09:14:56] [warn]: 	No Cron settings available.
[2021-09-14 09:14:56] [info]: 	Hassio API : Go !
[2021-09-14 09:14:58] [info]: 	Nextcloud connection : Go !
[2021-09-14 09:15:14] [info]: 	Stopping addons...
[2021-09-14 09:15:14] [info]: 	Starting addons...`

Any clue?

/Kasper

**Comment by Sebclem** [comment]
I have found the issue, I'm currently deploying the quick fix.

Thank for reporting this issue :sweat_smile:

**Comment by Sebclem** [comment]
Patch deployed, let me know if this fix your issue

**Comment by macsatcom** [comment]
It is not available in my HA as an upgrade, do I need to do a more manual
install of the fix?

**Comment by Sebclem** [comment]
You just need to force check for update:
Just go to Supervisor -> Addon Store -> 3 dots on top right -> Reload

**Comment by macsatcom** [comment]
You sire crushed that bug, but now I am getting:

`-----------------------------------------------------------
 Add-on: Nextcloud Backup
 Easily backup your Home Assistant snapshots to Nextcloud
-----------------------------------------------------------
 Add-on version: 0.16.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.6
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:01:19] INFO: Starting Node...
> nexcloud-backup@0.8.0 start
> node ./bin/www
[2021-09-14 13:01:24] [info]: 	Satus : Go !
[2021-09-14 13:01:24] [info]: 	Initializing and checking webdav client...
[2021-09-14 13:01:24] [info]: 	Starting auto clean cron...
[2021-09-14 13:01:25] [info]: 	Starting Cron...
[2021-09-14 13:01:25] [info]: 	Hassio API : Go !
[2021-09-14 13:01:25] [debug]: 	Home assistant sensor updated (error status)
[2021-09-14 13:01:25] [debug]: 	Home assistant sensor updated (status)
[2021-09-14 13:01:25] [debug]: 	Nextcloud connection:  Success !
[2021-09-14 13:01:26] [debug]: 	Path /Hassio Backup/ created.
[2021-09-14 13:01:27] [info]: 	Nextcloud connection : Go !
[2021-09-14 13:01:43] [info]: 	Stopping addons...
[2021-09-14 13:01:43] [info]: 	... Ok
[2021-09-14 13:01:43] [info]: 	Creating new snapshot...
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (status)
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (error status)
[2021-09-14 13:01:44] [error]: 	Can't create new snapshot (Response code 400 (Bad Request))
(node:346) UnhandledPromiseRejectionWarning: Can't create new snapshot (Response code 400 (Bad Request))
(Use `node --trace-warnings ...` to show where the warning was created)
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (error status)
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (status)
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (error status)
[2021-09-14 13:01:44] [debug]: 	Home assistant sensor updated (status)`

**Comment by Sebclem** [comment]
I need some additional information:
- Nextcloud installation method
- Reverse proxy in front of Nextcloud
- I need your Nextcloud logs too

**Comment by macsatcom** [comment]
NextCloud is native on Debian Machine (in a VM)
No proxy, HA and NextCloud is on same network. HA connects fine, and has
created the directories needed.

I see this error in NC log:

{"reqId":"3ADnwoxuLn44IwpXdt5D","level":0,"time":"2021-Sep-14
12:41:44","remoteAddr":"192.168.1.66","user":"--","app":"documentserver_community","method":"PROPFIND","url":"/remote.php/webdav/Hassio%20Backup/Auto/","message":"/appinfo/app.php
is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the
application class
instead.","userAgent":"axios/0.21.4","version":"21.0.0.18"}

**Comment by Sebclem** [comment]
I don't think this error is related, do you see anything inside apache logs ? 

It's very strange because i can't reproduce this error...
